// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/business-card/Bold.tsx": () => import("../components/mockups/business-card/Bold.tsx"),
  "./components/mockups/business-card/Classic.tsx": () => import("../components/mockups/business-card/Classic.tsx"),
  "./components/mockups/business-card/Minimal.tsx": () => import("../components/mockups/business-card/Minimal.tsx")
};
